using System;
using System.Collections.Generic;
using System.Drawing;

namespace GameEngine.Core.Shapes
{
    /// <summary>
    /// Class representing a line between two points.
    /// </summary>
    public class Line
    {
        /// <summary>
        /// The points representing the line are generated by Bresenham's line algorithm.
        /// </summary>
        public List<Vector2> Points { get; set; }

        /// <summary>
        /// Initializes a new instance of the <see cref="Line"/> class.
        /// </summary>
        /// <param name="a">The start point.</param>
        /// <param name="b">The end point.</param>
        public Line(Vector2 a, Vector2 b)
        {
            Points = new List<Vector2>();
            double deltaX = b.x - a.x;
            double deltaY = b.y - a.y;
            double deltaE = deltaY / deltaX;
            double error = deltaE;
            double y = a.y;

            for (double x = a.x; x <= b.x; x += 1)
            {
                Points.Add(new Vector2(x, y));

                if (error >= 1)
                {
                    error -= 1;
                    y += 1;
                }
                error += deltaE;
            }
        }

        /// <summary>
        /// Convert the list of vectors (double) to points on the screen (int).
        /// </summary>
        /// <returns>Array of screen points.</returns>
        public virtual Point[] GetPoints()
        {
            List<Point> points = new List<Point>();
            for (int i = 0; i < Points.Count; ++i)
            {
                points.Add(new Point((int)Points[i].x, (int)Points[i].y));
            }
            return points.ToArray();
        }
    }
}
