using System;
using System.Collections.Generic;
using System.Drawing;

namespace GameEngine.Core.Shapes
{
    /// <summary>
    /// Class representing a line between two points.
    /// </summary>
    public class Line
    {
        /// <summary>
        /// The points representing the line are generated by Bresenham's line algorithm.
        /// </summary>
        public List<Vector2> Points { get; set; }

        public Line(Vector2 a, Vector2 b)
        {
            Points = new List<Vector2>();
            Points.Add(a);
            Points.Add(b);
        }

        /// <summary>
        /// Convert the list of vectors (double) to points on the screen (int).
        /// </summary>
        /// <returns>Array of screen points.</returns>
        public virtual Point[] GetPoints()
        {
            List<Point> points = new List<Point>();
            for (int i = 0; i < Points.Count; ++i)
            {
                points.Add(new Point((int)Points[i].x, (int)Points[i].y));
            }
            return points.ToArray();
        }
    }
}
